name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Team awesome's approval workflow
    runs-on: ubuntu-latest
    steps:
      - name: Set approved label
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
